### ISSUE TITLE
Send soundboard files as audio messages

### ISSUE THREAD

**Issue by PatrickLemke** [PatrickLemke/einundzwanzigbot#36]
It should be possible to get the sound clips from https://einundzwanzig.space/soundboard/ as an audio message.
They can then be forwarded to other groups.

**Comment by dennisreimann** [comment]
Here's the JSON: https://einundzwanzig.space/sounds.json

**Comment by PatrickLemke** [comment]
@dennisreimann Do you know what the API endpoint will be?

**Comment by dennisreimann** [comment]
The API is the JSON file I posted :)

Can adapt it to whatever is needed, just let me know.

**Comment by PatrickLemke** [comment]
Thanks, looks good. I think I got confused because of another link to the GitHub repository.
